name: InfectionGame
version: '1.0-SNAPSHOT'
main: org.example.sawcka.InfectionGame.InfectionGame
api-version: '1.20'

commands:
  test:
    usage: /test
    permission: op


  drug:
    description: "Выдать лекарство себе"
    usage: /drug
    permission: op

  healer:
    description: "Заспавнить жителя с лекарством"
    usage: /healer <max_trades> <x> <y> <z> <is_ai:true|false> <exp_reward>
    permission: op

  infect:
    description: "Заразить игрока"
    usage: /infect <player>
    permission: op

  list_infected:
    description: "Список зараженных игроков"
    usage: /list_infected
    permission: op

  remove_infection:
    description: "Убрать заражение игрока"
    usage: /remove_infection <player>
    permission: op

  set_stage:
    description: "Установить текущую стадию болезни"
    usage: /set_stage <player> <stage>
    permission: op

  spawn_wave:
    description: "Заспавнить волну врагов в радиусе от точки <x> <y> <z>"
    usage: /spawn_wave <x> <y> <z> <radius> <difficulty>
    permission: op

  toggle_infinite_weather:
    description: "Включить/выключить бесконечную погоду"
    usage: /toggle_infinite_weather <rain|thunder>
    permission: op

  toggle_portal_blackout:
    description: "Включить/выключить ломание порталов"
    usage: /toggle_portal_blackout
    permission: op

  toggle_explode_creeper:
    description: "Включить/выключить подрыв криперов при ударе"
    usage: /toggle_explode_creeper
    permission: op

  wave_delayed:
    description: "Уведомление волны"
    usage: /wave_notify <x> <y> <z> <radius> <difficulty> <timeout:minutes>
    permission: op

  toggle_healer_auto_spawn:
    description: "Включить/выключить автоматический спавн жителя с 1 трейдом"
    usage: /toggle_healer_auto_spawn
    permission: op

  set_infection_duration:
    description: "Установить длительность стадии"
    usage: /set_infection_duration duration
    permission: op